version: '3'

volumes:
  pubsub_data:
    driver: local

services:
  pubsub:
    build:
      dockerfile: Dockerfile
      context: '.'
    environment:
      - PUBSUB_PROJECT_ID=project-test
      - PUBSUB_LISTEN_ADDRESS=0.0.0.0:8432
    ports:
      - 8432:8432
    volumes:
      - pubsub_data:/opt/data
      - ./pubsubpoc:/app